require("prototypes.recipe")
require("prototypes.item")
require("prototypes.entity")
require("prototypes.technology")
require("prototypes.equipment")
require("prototypes.style")
require("prototypes.hotkey")